### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by xavi-**
Implemented a number of general performance optimizations:

- Define regexs once at the top of the file
- Replaced .* with .+
- Special cased non-nested fields (i.e. fields without .'s)
- Replaced main `.map`,  `.some`, `.all`, `.filter` and `_.mapObject` calls with for-loops
- Took advantage of `Object.assign` when available
- Eliminated `_.deepClone` calls
- Reduce the number of uses of `_.extend/.assign` and `_.default`
- A lot of voodoo around inlining functions and code duplication
 
These changes resulted in a 10x speed increase across the board:

screen shot 2016-11-11 at 1 44 58 pm

The same graphs but without the pathological results:

screen shot 2016-11-11 at 1 49 42 pm

A zoomed in graph of the final performance (excluding the pathological case) results:

screen shot 2016-11-11 at 2 00 46 pm

At this point the performance of kayvee-js is comparable to kayvee-go, especially if you don't consider the pathological case:

screen shot 2016-11-11 at 1 55 04 pm

Possible performance improvements:
- Pre-parse strings with substitutions into an array and use `.join` instead of regex replacements
- Find a more performant version of `Object.assign` / `_.extend`.  Kayvee-js performance very badly with large (>4k) log lines

Things I tried, but didn't work:
- Inlining all the functions.  In some cases it hurt performance.
- Converting matchers into maps of maps (opposed to maps of arrays).  This had almost no effect.  What little change that appeared was mostly negative.
- Replacing `Object.assign` / `_.extend` with for-loops.  Again no or negative change.
- Replacing underscore with lodash.  Lodash made the benchmarks significantly slower

Context: https://clever.atlassian.net/browse/INFRA-2061
Data: https://docs.google.com/spreadsheets/d/1nOStru7gNPF1ETcJiso4sa9jQTNAp_BhJo1kIz6C5ZI/edit#gid=867566411

### CODE REVIEW

**Comment by jiancheung** [comment]
this is a work of art!

**Comment by jiancheung** [comment]
Very surprising that lodash was slower

**Comment by jiancheung** [comment]
lgtm! Did you consider including your benchmark tests so we can track perf regressions?

**Comment by xavi-** [comment]
I just updated the `.drone.yml` to run benchmarks are every build: 72824fd420559b4931a281ec935b847028752beb

**Pull request merged**
