### PR TITLE
decaffeinate.

### PR DESCRIPTION
**Pull request by nathanleiby**
Decaffeinated using https://github.com/decaffeinate/decaffeinate (ab8ec23)

Made some fixes to make Typescript compiler happier (see changes to `.ts` files in 806eaac)

Updated `.drone.yml` to install Node5: 5df204b

Also cleaned up Makefile to remove unused functionality
  - test-cov
  - publish

### CODE REVIEW

**Comment by nathanleiby** [comment]
This is also in preparation to add more JS code, for express logging middleware

**Comment by nathanleiby** [comment]
See some additional context here: https://clever.slack.com/archives/node/p1460423191000404

**Comment by nathanleiby** [comment]
@azylman worked with @jefff to get this updated to use typescript ... There's still some work to do to use full ES6 syntax, but I'll save that for a future pass

**Comment by azylman** [comment]
lgtm!

**Comment by rgarcia** [comment]
@nathanleiby looks like this is missing our eslint.yml (you can grab it from the launchpad repo)

**Comment by nathanleiby** [comment]
@rgarcia thanks for the catch - i had added it locally but not in revision control. added here: 427207af0b2020bc64b0157aad7ec53c46c6f2f9

**Pull request merged**
