### PR TITLE
add team field

### PR DESCRIPTION
**Pull request by ghirsch1**
same change from https://github.com/Clever/kayvee-go/pull/84

### CODE REVIEW

**Comment by ghirsch1** [comment]
weird, unclear why the linting isn't failing on the lines right below this 🤔

**Comment by ghirsch1** [comment]
yeah, I was just trying to keep it as in-line as possible

**Comment by taylor-sutton** [comment]
Also, whoops a little late but did you need to bump version on this to get the new version on NPM?

**Comment by ghirsch1** [comment]
oops, yeah I'll do that

**Pull request merged**
